apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
  annotations:
    # Notification triggers
    notifications.argoproj.io/subscribe.on-deployed.slack: k8s-deployment-status
    notifications.argoproj.io/subscribe.on-sync-failed.slack: k8s-deployment-status
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: k8s-deployment-status
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argoproj
    targetRevision: HEAD
    path: rollouts-demo
    # If you are using a raw manifest or helm, 
    # ensure the image is set to argoproj/rollouts-demo:blue
  destination:
    server: https://kubernetes.default.svc
    namespace: rollouts-demo-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
