apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tktucker/gitops-argocd.git'
    targetRevision: HEAD
    path: notifications/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
