apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo
  namespace: demo-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-service
  namespace: demo-apps
spec:
  selector:
    app: rollouts-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007 # Example random port in range 30000-32767
  type: NodePort
